# Generated by Django 5.2.6 on 2025-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
