# Generated by Django 5.2.5 on 2025-09-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0003_chairman_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='member_type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('officer', 'Officer'), ('staff', 'Staff')], default='faculty', max_length=20),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('ex_chairman', 'Ex-Chairman'), ('past_faculty', 'Past Faculty')], default='active', max_length=20),
        ),
    ]
