# Generated by Django 5.2.5 on 2025-09-19 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0004_facultymember_end_date_facultymember_member_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultymember',
            options={},
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='member_type',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_type', models.CharField(choices=[('officer', 'Officer'), ('staff', 'Staff')], max_length=20)),
                ('designation', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('past_staff', 'Past Staff')], default='active', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('room_no', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='staff/')),
                ('bio', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_date'],
            },
        ),
    ]
