# Generated by Django 5.2.5 on 2025-09-19 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0006_scrollingnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
