# Generated by Django 5.2.5 on 2025-09-19 12:59

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0007_alter_notice_board_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
