# Generated by Django 5.2.5 on 2025-09-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0008_auto_20250919_1859'),
    ]

    operations = [
    ]
