# Generated by Django 5.2.5 on 2025-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0009_auto_20250919_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
