# Generated by Django 5.2.5 on 2025-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0012_carouselitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
