# Generated by Django 5.2.5 on 2025-09-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0014_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='club/computer_club/')),
                ('position', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('general_secretary', 'General Secretary'), ('assistant_general_secretary', 'Assistant General Secretary'), ('treasurer', 'Treasurer'), ('editor_secretary', 'Editor Secretary'), ('programming_secretary', 'Programming Secretary'), ('assistant_programming_secretary', 'Assistant Programming Secretary'), ('sports_secretary', 'Sports Secretary'), ('assistant_sports_secretary', 'Assistant Sports Secretary'), ('event_management_secretary', 'Event Management Secretary'), ('publicity_secretary', 'Publicity & Publication Secretary'), ('assistant_publicity_secretary', 'Assistant Publicity & Publication Secretary'), ('assistant_information_secretary', 'Assistant Information Secretary'), ('assistant_organizing_secretary', 'Assistant Organizing Secretary')], max_length=50)),
            ],
            options={
                'verbose_name': 'Computer Club Member',
                'verbose_name_plural': 'Computer Club Members',
                'ordering': ['position'],
            },
        ),
    ]
