# Generated by Django 5.2.5 on 2025-09-24 16:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0020_fix_notice_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultymember',
            options={'ordering': ['designation', 'name'], 'verbose_name': 'Faculty Member', 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.AddField(
            model_name='facultymember',
            name='awards_honors',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Awards and honors received'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='courses_taught',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Courses taught'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload CV/Resume', null=True, upload_to='faculty/cv/'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='google_scholar_url',
            field=models.URLField(blank=True, help_text='Google Scholar profile URL'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='member_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('visiting', 'Visiting'), ('adjunct', 'Adjunct')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='membership',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Professional memberships'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='orcid_url',
            field=models.URLField(blank=True, help_text='ORCID profile URL'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='others',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Other relevant information'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='personal_website',
            field=models.URLField(blank=True, help_text='Personal website URL'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='professional_experience',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Professional experience'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='publications',
            field=ckeditor.fields.RichTextField(blank=True, help_text='List of publications'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='research_activities',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Research activities and projects'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='research_gate_url',
            field=models.URLField(blank=True, help_text='ResearchGate profile URL'),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Educational background'),
        ),
    ]
