# Generated by Django 5.2.5 on 2025-09-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0021_alter_facultymember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(help_text='e.g., BSc, MSc, PhD, Diploma', max_length=200)),
                ('major_subject', models.CharField(help_text='Group/Major Subject', max_length=200)),
                ('board_institute', models.CharField(help_text='Board/Institute/University name', max_length=200)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('passing_year', models.IntegerField(help_text='Year of graduation/completion')),
                ('grade_gpa', models.CharField(blank=True, help_text='Grade/GPA/Result (optional)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order for display (0 for latest)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cse_app.facultymember')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Records',
                'ordering': ['order', '-passing_year'],
            },
        ),
    ]
