# Generated by Django 5.2.5 on 2025-09-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0022_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(help_text='Award/Honor title', max_length=200)),
                ('award_type', models.CharField(choices=[('academic', 'Academic Award'), ('research', 'Research Award'), ('teaching', 'Teaching Award'), ('service', 'Service Award'), ('fellowship', 'Fellowship'), ('scholarship', 'Scholarship'), ('recognition', 'Recognition'), ('other', 'Other')], max_length=20)),
                ('awarding_organization', models.CharField(help_text='Organization that gave the award', max_length=200)),
                ('year', models.IntegerField(help_text='Year received')),
                ('description', models.TextField(blank=True, help_text='Description of the award')),
                ('amount', models.CharField(blank=True, help_text='Award amount (if applicable)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order for display (0 for latest)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_records', to='cse_app.facultymember')),
            ],
            options={
                'verbose_name': 'Award Record',
                'verbose_name_plural': 'Award Records',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='Course code (e.g., CSE101)', max_length=20)),
                ('course_title', models.CharField(help_text='Course title', max_length=200)),
                ('course_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('professional', 'Professional Development')], max_length=20)),
                ('course_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Laboratory'), ('project', 'Project'), ('seminar', 'Seminar'), ('thesis', 'Thesis Supervision')], max_length=20)),
                ('semester', models.CharField(help_text='Semester/Term (e.g., Fall 2023)', max_length=20)),
                ('credit_hours', models.DecimalField(decimal_places=1, help_text='Credit hours', max_digits=3)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('order', models.IntegerField(default=0, help_text='Order for display (0 for latest)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_records', to='cse_app.facultymember')),
            ],
            options={
                'verbose_name': 'Course Record',
                'verbose_name_plural': 'Course Records',
                'ordering': ['order', '-semester'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(help_text='Organization/Society name', max_length=200)),
                ('membership_type', models.CharField(choices=[('professional', 'Professional Organization'), ('academic', 'Academic Society'), ('editorial', 'Editorial Board'), ('committee', 'Committee Member'), ('reviewer', 'Reviewer'), ('other', 'Other')], max_length=20)),
                ('position', models.CharField(blank=True, help_text='Position/Role (if any)', max_length=100)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if ongoing)', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Currently active membership')),
                ('description', models.TextField(blank=True, help_text='Additional details about the membership')),
                ('order', models.IntegerField(default=0, help_text='Order for display (0 for latest)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_records', to='cse_app.facultymember')),
            ],
            options={
                'verbose_name': 'Membership Record',
                'verbose_name_plural': 'Membership Records',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(help_text='Job title/position', max_length=200)),
                ('organization', models.CharField(help_text='Organization/Company name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Location (City, Country)', max_length=100)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently working here')),
                ('description', models.TextField(blank=True, help_text='Job description/responsibilities')),
                ('order', models.IntegerField(default=0, help_text='Order for display (0 for latest)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_experiences', to='cse_app.facultymember')),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Publication title', max_length=300)),
                ('authors', models.CharField(help_text='All authors (comma-separated)', max_length=500)),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('chapter', 'Book Chapter'), ('thesis', 'Thesis'), ('report', 'Technical Report'), ('other', 'Other')], max_length=20)),
                ('venue', models.CharField(help_text='Journal/Conference/Publisher name', max_length=200)),
                ('year', models.IntegerField(help_text='Publication year')),
                ('volume', models.CharField(blank=True, help_text='Volume (if applicable)', max_length=20)),
                ('pages', models.CharField(blank=True, help_text='Page numbers (if applicable)', max_length=20)),
                ('doi', models.CharField(blank=True, help_text='DOI (if available)', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Publication URL (if available)')),
                ('order', models.IntegerField(default=0, help_text='Order for display (0 for latest)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_records', to='cse_app.facultymember')),
            ],
            options={
                'verbose_name': 'Publication Record',
                'verbose_name_plural': 'Publication Records',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ResearchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Research activity title', max_length=200)),
                ('activity_type', models.CharField(choices=[('project', 'Research Project'), ('publication', 'Publication'), ('grant', 'Research Grant'), ('collaboration', 'Research Collaboration'), ('supervision', 'Student Supervision'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Description of the research activity')),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if ongoing)', null=True)),
                ('is_ongoing', models.BooleanField(default=False, help_text='Currently ongoing')),
                ('funding_agency', models.CharField(blank=True, help_text='Funding agency (if any)', max_length=200)),
                ('collaborators', models.CharField(blank=True, help_text='Collaborators/Co-researchers', max_length=300)),
                ('order', models.IntegerField(default=0, help_text='Order for display (0 for latest)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_activity_records', to='cse_app.facultymember')),
            ],
            options={
                'verbose_name': 'Research Activity',
                'verbose_name_plural': 'Research Activities',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
