# Generated by Django 5.2.5 on 2025-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0023_awardrecord_courserecord_membershiprecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserecord',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='membershiprecord',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='publicationrecord',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='researchactivity',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='education',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='professional_experience',
        ),
        migrations.DeleteModel(
            name='AwardRecord',
        ),
        migrations.DeleteModel(
            name='CourseRecord',
        ),
        migrations.DeleteModel(
            name='MembershipRecord',
        ),
        migrations.DeleteModel(
            name='PublicationRecord',
        ),
        migrations.DeleteModel(
            name='ResearchActivity',
        ),
    ]
