# Generated by Django 5.2.5 on 2025-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0024_remove_courserecord_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Is this faculty member currently active?'),
        ),
    ]
