# Generated by Django 5.2.6 on 2025-10-15 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_app', '0025_facultymember_is_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=150, help_text='Total number of enrolled students in the department')),
                ('total_faculty', models.IntegerField(default=0, help_text='Total number of active faculty members (auto-calculated if set to 0)')),
                ('total_labs', models.IntegerField(default=3, help_text='Number of computer labs in the department')),
                ('total_research_areas', models.IntegerField(default=0, help_text='Number of research focus areas (auto-calculated if set to 0)')),
                ('total_publications', models.IntegerField(default=0, help_text='Total research publications (auto-calculated if set to 0)')),
                ('total_projects', models.IntegerField(default=0, help_text='Total research/academic projects (auto-calculated if set to 0)')),
                ('total_alumni', models.IntegerField(blank=True, default=0, help_text='Total number of alumni (optional)')),
                ('established_year', models.IntegerField(default=2019, help_text='Year the department was established')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about statistics updates')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who updated the statistics', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Statistics',
                'verbose_name_plural': 'Department Statistics',
            },
        ),
    ]
